source 'http://rubygems.org'

path "/home/gerry/work/decko" do
  gem 'decko'
  gem 'card', :require => false
  gem 'cardname', :require => false
end

# development in card-mods, existing or new
#gem 'card-mod-X', path: '/home/gerry/work/card-mods/X'
gem 'card-mod-csv_import', path: '/home/gerry/work/card-mods/csv_import'
gem 'card-mod-airbrake', path: '/home/gerry/work/card-mods/airbrake'

gem 'mysql2', '>= 0.4.4'

# WEBSERVER
# To run a simple deck at localhost:3000, you can use thin (recommended), unicorn, or (Rails' default) Webrick
gem 'thin'
# gem 'unicorn'

# To set up a production webserver, see https://decko.org/wagn_in_production


# BACKGROUNDING
# The daemons gem is needed to run tasks like sending notifications in a background process.
# See config/application.rb for configuration details.
# gem 'daemons'


group :test do
  gem 'capybara-puma'
  gem 'rspec'
  gem 'rspec-rails', '~>4.0.0.beta2'         # behavior-driven-development suite
  gem 'spork', '>=0.9'
  gem 'rubocop', '~>0.88.0'
  gem 'rubocop-decko'
  gem 'nokogumbo'
end

group :test, :cypress do
  gem 'cypress-on-rails', '~> 1.4'
end

group :test, :development do
  gem 'colorize'
  gem 'delayed_job_active_record', '~> 4.1'
  gem 'html2haml'
  # gem 'jasmine'
  # gem 'jasmine-rails'
  # gem 'jasmine-jquery-rails'
  gem 'sprockets' # just so above works
  gem 'phantomjs', '1.9.7.1' #locked because 1.9.8.0 is breaking

  gem 'better_errors'
  gem 'binding_of_caller'


  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'listen', '3.0.6'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'spring-commands-cucumber'
  end

group :debug do
  gem 'pry-rails'
  gem 'pry-rescue'
  gem 'pry-stack_explorer'
  gem 'pry-byebug'
end

group :test do
  gem 'timecop', '=0.3.5' 
end


# load gems needed in Gemfiles
# You may need to alter this code if you move your mod(s) to an unconventional location.
Dir.glob( 'mod/**{,/*/**}/Gemfile' ).each do |gemfile|
  instance_eval File.read(gemfile)
end
